### PR TITLE
Fix 202

### PR DESCRIPTION
**Pull request by dagkalis**
Fixes issue #202. 
After the division by 0, the 0 is removed and the operation stays division (does not turn to addition).

Sample: 
https://user-images.githubusercontent.com/56542304/131219726-1e2db836-9c98-473a-859d-d89e2221b8e0.mp4

### CODE REVIEW

**Comment by tibbi** [comment]
thanks, but I dont really like such automatic value changes

**Comment by dagkalis** [comment]
> thanks, but I dont really like such automatic value changes

I see. I can make it so that no value is changed but the bug is fixed. Does this interest you?

**Comment by tibbi** [comment]
which bug?

**Comment by dagkalis** [comment]
After dividing by zero the operation changes to addition even though it should stay division. it is described in issue #202.

**Comment by tibbi** [comment]
lets keep it as it is for now

**Pull request closed without merging**
