### PR TITLE
update to latest commons

### PR DESCRIPTION
**Pull request by FunkyMuse**

### CODE REVIEW

**Comment by tibbi** [comment]
found just 1 issue, the navigation bar doesnt change its color properly in onResume, when you toggle between light and dark theme in Customize colors. Would be good to have it working well, but isnt a critical issue.

**Comment by FunkyMuse** [comment]
> found just 1 issue, the navigation bar doesnt change its color properly in onResume, when you toggle between light and dark theme in Customize colors. Would be good to have it working well, but isnt a critical issue.

Does that happen on the customization screen or on the Settings screen inside Calculator?

**Comment by FunkyMuse** [comment]
Waiting on https://github.com/SimpleMobileTools/Simple-Commons/pull/1836

**Comment by tibbi** [comment]
yeah thanks, looks good

**Pull request merged**
