### PR TITLE
Add Scientific Operations

### PR DESCRIPTION
**Pull request by AhmedAshrafHamza**
1-Add Sin,Cos,Tan,Arcsin,Arccos and Arctan features to Scientific Activity with test cases 
2-Activate Scientific activity with added operations

### CODE REVIEW

**Comment by tibbi** [comment]
update the code style please, regarding the spaces and new lines. No need to work on tests, I dont really want to maintain them in the future

**Comment by AhmedAshrafHamza** [comment]
i tried to to apply code style.
Is it okay now ?
and thank you for help .

**Comment by tibbi** [comment]
I didnt mean removing newlines, just check some other files... I mean spacing in the code itself, like "}else if(sign == "Arctan("){", or at `if(operation==Tan)
        {`
Plus remove the multiple empty lines after each other from every file.

**Comment by AhmedAshrafHamza** [comment]
which empty lines? ,i can not recognize

**Comment by tibbi** [comment]
alright, nevermind, I will tweak the UI things. But Ill also remove the copyrights as they arent present in any files. Thanks

**Comment by tibbi** [comment]
or nevermind, updating this solution would be really more work than writing it from scratch :/ The layouts, functions and constants are all messed up. Thanks though.

**Comment by AhmedAshrafHamza** [comment]
thank you very much for your help .. :)
is anything required from us ?

**Comment by tibbi** [comment]
no, since I actually reverted the pull request. I will work on it someday in the future.

**Pull request merged**
