### PR TITLE
Larger Precision Calculation

### PR DESCRIPTION
**Pull request by vyasknellutla**
- Moved to using BigDecimal instead of Double for most methods
- Replaced Deprecated Methods/Classes
- Fixed some Android Linter issues

### CODE REVIEW

**Comment by vyasknellutla** [comment]
This should resolve Issue #19

**Comment by vyasknellutla** [comment]
Hi @tibbi,

Are there any changes you'd like made to this PR?

**Comment by vyasknellutla** [comment]
Would you prefer that it was broken up into smaller changes?

**Comment by tibbi** [comment]
Im not working on the calculator now, will take a look at it a bit later. Seems good on the first sight

**Comment by tibbi** [comment]
seems to work well. Thanks

**Pull request merged**
