### PR TITLE
Improve italian translations

### PR DESCRIPTION
**Pull request by ema-pe**
Hi! I'm revisioning all translations, improving the quality of all strings. This is the first app I've checked.

### CODE REVIEW

**Comment by tibbi** [comment]
thanks, app names should be translated too though

**Comment by tibbi** [comment]
ye but if someone doesnt speak english he might have a hard time finding the app. Maybe the calculator is said similarly in many languages, but some other apps might use a whole different word.

**Comment by ema-pe** [comment]
In Italian the app's name should be "Calcolatrice semplice", "semplice" is the translation for "Simple", but in Italian it doesn't sound good. An option is to remove "semplice" in the translation, and the name became only "Calcolatrice". Is it too anonymous?

On 21 December 2018 15:33:36 CET, Tibor Kaputa <notifications@github.com> wrote:
>ye but if someone doesnt speak english he might have a hard time
>finding the app. Maybe the calculator is said similarly in many
>languages, but some other apps might use a whole different word.

-- 
Emanuele

Sent from my mobile, excuse my brevity.

**Comment by ema-pe** [comment]
@tibbi I found a solution. The name in italian will be "Semplice Calcolatrice". It sounds better than "Calcolatrice Semplice", but instead of "Calcolatrice" this translation has "Semplice", a clear sign of this "brand". I'm making the pull requests in these days for all applications.

**Comment by tibbi** [comment]
well I cannot say which sounds better, do it however you think :) Thanks

**Pull request merged**
