### PR TITLE
Update values-el

### PR DESCRIPTION
**Pull request by spkprs**
ΟΚ?

### CODE REVIEW

**Comment by tibbi** [comment]
yeah, thanks

**Comment by spkprs** [comment]
Please put file in a folder with rights names

**Comment by tibbi** [comment]
what do you mean?

**Comment by spkprs** [comment]
folder >values-el>strings.xml

**Comment by spkprs** [comment]
I don't know in github how to make

**Comment by tibbi** [comment]
ye, I added it already

**Comment by spkprs** [comment]
The file in your git is out from folder, and the name is wrong 😉

Στάλθηκε από την Αλληλογραφία για Windows 10

Από: Tibor Kaputa
Αποστολή: Wednesday, November 13, 2019 22:29
Προς: SimpleMobileTools/Simple-Calculator
Κοιν.: spkprs; Author
Θέμα: Re: [SimpleMobileTools/Simple-Calculator] Update values-el (#136)

ye, I added it already

**Comment by tibbi** [comment]
aha I see, fixed it. Thanks

**Pull request merged**
