### PR TITLE
fix: customize colors locked

### PR DESCRIPTION
**Pull request by FunkyMuse**

### CODE REVIEW

**Comment by tibbi** [comment]
looks good now, but it isnt clickable... Make it work like previously, so that it shows the FeatureLockedDialog on click.

**Comment by tibbi** [comment]
settings look good already, but the widget creation screen with Feature Locked still has display issues. I mean the WidgetConfig screen doesnt have proper dialog colors. Lets also allow closing the dialog with pressing Back or outside the dialog, treat it like pressing Later.

**Comment by tibbi** [comment]
the Rate Stars Dialog should be rewritten as quickly as possible too, it is present in all apps and not readable in About section with light material you theme

**Comment by tibbi** [comment]
@FunkyMuse can you please update this before rewriting the more advanced dialogs?

**Comment by tibbi** [comment]
"English" in the app settings should use lower alpha than "Language"

**Comment by FunkyMuse** [comment]
> "English" in the app settings should use lower alpha than "Language"

done

**Pull request merged**
